name: trendify
type: php:8.2

build:
  flavor: none
  commands:
    - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
    - php artisan key:generate --no-interaction --force
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan view:clear
    - php artisan route:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan storage:link

deploy:
  commands:
    - php artisan migrate --force --no-interaction
    - php artisan optimize:clear
    - php artisan optimize

mounts:
  /storage: shared
  /bootstrap/cache: shared
  /public/storage: shared

web:
  locations:
    /:
      root: public
      passthru: /index.php
      index:
        - index.php
      try_files:
        - $uri
        - $uri/
        - /index.php?$query_string
      expires: 1h
      headers:
        Cache-Control: "public, max-age=3600"
        X-Frame-Options: "SAMEORIGIN"
        X-Content-Type-Options: "nosniff"
        X-XSS-Protection: "1; mode=block"
        Referrer-Policy: "strict-origin-when-cross-origin"

crons:
  - spec: '*/15 * * * *'
    cmd: 'php artisan schedule:run'

environment:
  variables:
    APP_KEY: "base64:TGG244w3cR+gSzj+V6AlAfBNdQdC1+QzSPu2Hee3iTk="
    APP_NAME: "trendify"
    APP_ENV: "production"
    APP_DEBUG: "false"
    APP_URL: "https://trendify-master-jaozqq.laravel.cloud"
    LOG_CHANNEL: "laravel-cloud-socket"
    LOG_STDERR_FORMATTER: "Monolog\Formatter\JsonFormatter"
    SESSION_DRIVER: "cookie"
    VITE_APP_NAME: "${APP_NAME}" 